blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='all-blogs'),
    path('bloggers/', views.BloggerListView.as_view(), name='all-bloggers'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
    path('<int:pk>/comment', views.CommentCreate.as_view(), name='comment')
]

diyblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Blogger(models.Model):

    name = models.CharField(max_length=255)
    bio = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])


class Post(models.Model):

    title = models.CharField(max_length=255)
    content = models.TextField()
    date_add = models.DateField(auto_now_add=True)
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_add']
        permissions = (('can_create_new_post', 'Can create new post'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])


class Comment(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author.first_name} {self.author.last_name}"

    class Meta:
        ordering = ['date_add']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Post, Blogger, Comment
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

def index(request):
    num_bloggers = Blogger.objects.count()
    num_posts = Post.objects.count

    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    context = {
        'num_bloggers': num_bloggers,
        'num_posts': num_posts,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


class BlogListView(generic.ListView):
    model = Post
    paginate_by = 5

class BloggerListView(generic.ListView):
    model = Blogger


class BloggerDetailView(generic.DetailView):
    model = Blogger


class BlogDetailView(generic.DetailView):
    model = Post





class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['message']
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context


    def get_success_url(self):

        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}DIY Blog{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'all-blogs' %}">All blogs</a></li>
                <li><a href="{% url 'all-bloggers' %}">All bloggers</a></li>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    {% if perms.blog.can_create_new_post %}
                    <li><a href="">Create new post</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
            {% endif %}
            {% endblock %}

        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/blogger_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Blogger: {{ blogger.name }}</h1>

<h2>Bio</h2>
<p>{{ blogger.bio }}</p>
<h2>Blogs list</h2>
<div style="margin-left:20px;margin-top:20px;">
    <ul>
    {% for blog in blogger.post_set.all %}
        <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.date_add }})</li>
    {% endfor %}
        </ul>
</div>
{% endblock %}

blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1> All bloggers </h1>
{% if blogger_list %}
<ul>
    {% for blogger in blogger_list %}
    <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base_generic.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit"/>

</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>{{ post.title }}</h1>

<p><strong>Post date: </strong>{{ post.date_add }}</p>
<p>
    <strong>Author: </strong>
    <a href="{{ post.blogger.get_absolute_url }}">{{ post.blogger }}</a>
</p>
<p><strong>Description:</strong></p>
<p>{{ post.content }}</p>
<div style="margin-left:20px;margin-top:20px;">
    <h4>Comments</h4>
    {% for comment in post.comment_set.all %}
    <hr>
    <p>{{ comment.author }} ({{ comment.date_add }}) - {{ comment.message }}</p>
    {% endfor %}
    <hr>
    {% if user.is_authenticated %}
    <a href="{% url 'comment' post.id %}">Add a new comment</a>
    {% else %}
    <p><a href="{% url 'login'%}?next={{request.path}}">Login </a>to add a new comment</p>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1> All blogs </h1>
{% if post_list %}
<ul>
    {% for post in post_list %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post }}</a>
        ({{ post.date_add }}) -- <a href="{{ post.blogger.get_absolute_url}}">{{ post.blogger }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

blog/templates/index.html
{% extends 'base_generic.html' %}


{% block title %}Homepage | {{ block.super }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <h1>DIY Blog Home</h1>
            <p>Welcome to DIY Blog, my first site without help of tutorials!</p>
            <h2>Dynamic content</h2>
            <p>The Blog has the following record counts:</p>
            <ul>
                <li><strong>Posts:</strong> {{ num_posts }}</li>
                <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
            </ul>
            <p>You have visited this page {{ num_visits }} {% if num_visits == 1 %}time{% else %}times{% endif %}</p>
        </div>
        <div class="col-sm-4">
            {% load static %}
            <img src="{% static 'img/kitik.png' %}" alt="kitik" style="margin-top:70px;">
        </div>
    </div>
</div>
{% endblock %}